345207: Set the correct image update policy for the service templates
DEFRA/adp-portal-api pull request #18
Opened 2024-04-15 17:30 UTC by ajaysoni-cap

# **What this PR does / why we need it**:
Enhance he logic to set the correct image policy for the service patch files.
Relates to ADO Work Item AB#345207

# **Special notes for your reviewer**
N/A

# Testing
N/A

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-04-15 17:36 UTC, ppotturi submitted a review, later dismissed

2024-04-15 18:05 UTC, DaRoszko requested changes
up the version number

2024-04-15 20:30 UTC, kbabigumira approved these changes

2024-04-16 08:44 UTC, ajaysoni-cap commented
> up the version number

2024-04-16 08:44 UTC, ajaysoni-cap commented
> > up the version number

Updated.

2024-04-16 09:13 UTC, DaRoszko submitted a review, later dismissed

2024-04-16 10:23 UTC, adp-platform approved these changes

2024-04-16 10:25 UTC, adp-platform approved these changes

2024-04-16 10:52 UTC, adp-platform approved these changes

2024-04-16 10:53 UTC, merged